### PR TITLE
improve Rust

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by boyanio** [comment]
Hey Max,

Thank you for the PR. As I am not much into Rust, could you please explain the changes to me? Just of curiosity, in order to understand what's happening under the hood :-)

Best,
Boyan

**Comment by MaxGraey** [comment]
Sure!
1). Additional `-Oz -C lto` flags mean we want compile code with size tuning and turn on link time optimization.
2) `pub fn panic(_info: &PanicInfo) -> !` mean we rewrite default `panic` mechanics with using built-in `unreachable` which reduce runtime size. This usual recommendation from [rust-wasm book](https://rustwasm.github.io/docs/book/reference/code-size.html)
3) `fn floor(x: f64) -> f64` use builtin intrinsic instead `std` which also reduce runtime size.

**Comment by boyanio** [comment]
Great, thank you!

Have you tried building it using Docker? I get `Unrecognized option 'z'`. I tried switching to Rust 1.33, but to no avail.

**Comment by MaxGraey** [comment]
Hmm, that's strange. Switched to another style using `-C opt-level=z`

**Comment by boyanio** [comment]
Now this works, but I get `error[E0554]: #![feature] may not be used on the stable release channel`

**Comment by MaxGraey** [comment]
Yeah, this nightly feature. Could you use  nightly or `rust:1.35`, `rust:latest`?

**Comment by boyanio** [comment]
Yes, I don't mind, but I cannot find an image in the official [Docker hub](https://hub.docker.com/_/rust). How would you do it?

**Comment by MaxGraey** [comment]
https://hub.docker.com/r/rustlang/rust/dockerfile

May be this?

**Comment by boyanio** [comment]
Nice! Can you update the Dockerfile with `FROM rustlang/rust:nightly`? Later on, when it becomes stable, I will move it back to the stable version

**Comment by MaxGraey** [comment]
Sure. Done!

**Pull request merged**
